name: Build and Release UWP & Console App

on:
  push:
    branches:
      - main
      - develop
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restaurer les dépendances NuGet
        run: nuget restore EasySave.sln

      - name: Compiler l'application en mode Release
        run: msbuild EasySave.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Publier EasySaveConsole (Console App) avec le profil de publication
        run: dotnet publish EasySaveConsole/EasySaveConsole.csproj /p:PublishProfile=FolderProfile.pubxml

      - name: Publier CryptoSoft (Console App) avec le profil de publication
        run: dotnet publish CryptoSoft/CryptoSoft.csproj /p:PublishProfile=FolderProfile.pubxml

      - name: Publier EasySaveGUI (UWP) avec le profil de publication
        run: dotnet publish EasySaveGUI/EasySaveGUI.csproj /p:PublishProfile=FolderProfile.pubxml
        
      - name: Télécharger l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: EasySave-Apps
          path: |
            EasySaveConsole/publish/
            EasySaveGUI/publish/
            CryptoSoft/publish/

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Télécharger l'artefact du build
        uses: actions/download-artifact@v4
        with:
          name: EasySave-Apps
          path: package/

      - name: Créer une Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: package/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
